### ISSUE TITLE
Burgershot breaks my inventory?

### ISSUE THREAD

**Issue by SoCallMeAstro** [DrBlackBeard095/qb-burgershot#1]
So i'm not sure if this is where I should ask for assistance, was gonna join your discord and try and ask there, but the link isn't working anymore.

Basically everything in the inventory was working fine, shops ect.

After I added the your burgershot script (good work btw love it!), it actually breaks all the shops and the inventory I'm guessing.
Cause all my items seemed to vanish after, or maybe something else caused that not sure.

Now the only thing that works is the burgershot shop and stuff, everything else however is broken.

Have any idea why? Sorry if that's a stupid question, just a little lost lol
Even if you can't help, thank you either way 💜

Here's the error I'm getting, this wasn't happening before I added the burgershot stuff. @aj-inventory/server/main.lua:931: attempt to index a nil value (local 'itemInfo')

**Comment by Zach488** [comment]
As i can see u are using aj inventory , i only tested the script on qb-inventory created and maintained by QBCore . But will try and have a look

**Comment by Zach488** [comment]
But what that error is , is trying to call a value(item) not created or added

**Comment by Zach488** [comment]
Make sure u followed the right instructions

**Comment by SoCallMeAstro** [comment]
I followed exactly what was there twice, and still got that same error. I'll try one more time and see if that helps at all.

**Comment by SoCallMeAstro** [comment]
Hmm yeah, I don't see anything wrong or missing strange

**Comment by Zach488** [comment]
Yea as i said i used it on qb-inventory , just revise the code and check if there is some different stuff with that inventory

**Comment by SoCallMeAstro** [comment]
Ok yeah it's just the inventory, alright thanks for the help!
