### ISSUE TITLE
clock in?

### ISSUE THREAD

**Issue by TripJaxon** [DrBlackBeard095/qb-burgershot#2]
Having trouble locating the clock in. Used the coords in the coding, but when I put my eye target on the area there's nothing. That's the only thing not working...I'm assuming it's something I didn't do right.

**Comment by Zach488** [comment]
Go and enable polyzone to see where u clock in not 100% sure where

**Comment by TripJaxon** [comment]
I enabled the polyzone debug, saw the greenbox to where I would clockin, still no interaction, doesn't turn the eye blue. If it didn't happen during your testing, then it's on my end. I was just unclear if it was an actual bug, or my plain ignorance.
