### ISSUE TITLE
Pay with Cash Option

### ISSUE THREAD

**Issue by ch0sguy** [DrBlackBeard095/qb-burgershot#8]
Would it be possible to implement a secondary option within the cash register as an employee, being "Bill with Cash", and once said employee enters respective price and etc. within the qb-menu interface, non-employees are then able to qb-target interact with the register, prompting a qb-menu "Pay with Cash" option, withdrawing from the user directly (as to implement more of a realistic approach to avoiding paper trails for police investigations and tracking)?

**Comment by Zach488** [comment]
Yea its not that hard to do , just use qb-menu

**Comment by ch0sguy** [comment]
Sorry, I guess my question was more oriented towards "would you consider adding it to your script" rather than would it be possible; if not, its no big deal, I'll configure it myself when I finish my server's police script, but I figured it'd be a nice feature for people to use regardless.
